const WEBPAGE_SYSTEM = `You are a web page generator for Beatrice. Create a COMPLETE, production-quality single-page HTML file. Include embedded CSS and JavaScript. Use a dark theme with warm peach (#d0a78b) accents. The page must be fully self-contained. Output ONLY raw HTML — no markdown, no code fences, no explanations. Start with <!DOCTYPE html>.`;

const DOCUMENT_HTML_SYSTEM = `You are a document writer for Beatrice — CEO-grade, boardroom-quality output. Create a COMPLETE, self-contained HTML document page with embedded CSS. Use a dark theme (#0a0a0b background) with warm peach (#d0a78b) accents. Include proper heading hierarchy (h1 title, h2 sections, h3 subsections), body text in #e4e4e7, cards for key points, bullet lists, blockquotes for citations, horizontal rules between major sections, and a professional footer with "Generated by Beatrice · Eburon AI" and the date. The document must be FULLY comprehensive — at least 800 words. Use proper spacing, readable typography (system-ui, 16px base), and responsive layout. Output ONLY raw HTML — no markdown, no code fences, no explanations. Start with <!DOCTYPE html>.`;

const DASHBOARD_SYSTEM = `You are a dashboard creator for Beatrice. Create a complete, interactive single-page dashboard in HTML with embedded CSS and JS. Use a dark theme with warm peach (#d0a78b) accents. Include metric cards, status indicators, activity lists, and performance bars. Output ONLY the raw HTML — no markdown wrappers, no code fences.`;

const CODE_SYSTEM = `You generate production-ready code. Output only the code with brief comments. Be thorough and correct.`;

function buildPrompt(taskType: string, prompt: string): { system: string; user: string } {
  switch (taskType) {
    case "webpage":
      return { system: WEBPAGE_SYSTEM, user: `Create a complete single-page website for: ${prompt}. Include navigation, hero section, feature cards, and footer. Dark theme, peach (#d0a78b) accent.` };
    case "dashboard":
      return { system: DASHBOARD_SYSTEM, user: `Create a full monitoring dashboard for: ${prompt}. Include metric cards, status indicators, activity bars. Dark theme.` };
    case "document":
    case "report":
      return { system: DOCUMENT_HTML_SYSTEM, user: `Write a comprehensive CEO-grade ${taskType} about: ${prompt}. Include an executive summary, detailed sections with analysis, key findings or recommendations, data points or evidence, and a conclusion. Be thorough — at least 800 words of substantive content.` };
    case "summarize":
      return { system: DOCUMENT_HTML_SYSTEM, user: `Create a clear, structured summary of: ${prompt}. Extract key points and present as an organized HTML document.` };
    case "code":
    case "fix":
      return { system: CODE_SYSTEM, user: `Generate working code for: ${prompt}. Production-ready with comments.` };
    default:
      return { system: DOCUMENT_HTML_SYSTEM, user: `Create content for: ${prompt}. Well-structured HTML document.` };
  }
}

export class EburonWorker {
  private baseUrl: string;
  private model: string;
  private fallbackModel: string | null;
  private fallbackUsed = false;
  private _alive = false;
  private lastCheck = 0;

  constructor(baseUrl: string, model: string, fallbackModel?: string) {
    this.baseUrl = baseUrl.replace(/\/$/, "");
    this.model = model;
    this.fallbackModel = fallbackModel || null;
  }

  get modelName() { return this.fallbackUsed ? this.fallbackModel! : this.model; }
  get didFallback() { return this.fallbackUsed; }

  async checkConnection(): Promise<boolean> {
    if (Date.now() - this.lastCheck < 30000) return this._alive;
    try {
      const res = await fetch(`${this.baseUrl}/api/tags`, { signal: AbortSignal.timeout(5000) });
      if (res.ok) {
        const data = await res.json();
        const found = (data.models || []).some((m: any) => m.name === this.model || m.name?.startsWith(this.model));
        this._alive = found;
        this.lastCheck = Date.now();
        return found;
      }
    } catch {}
    this._alive = false;
    this.lastCheck = Date.now();
    return false;
  }

  private async tryGenerate(model: string, type: string, prompt: string): Promise<{ content: string; fileType: string; title: string }> {
    const { system, user } = buildPrompt(type, prompt);
    const fullPrompt = `${system}\n\nTask: ${user}\n\nNow generate the complete output directly:`;

    const isBigOutput = type === "document" || type === "report" || type === "webpage" || type === "dashboard";

    const res = await fetch(`${this.baseUrl}/api/generate`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        model,
        prompt: fullPrompt,
        stream: false,
        options: {
          temperature: 0.7,
          top_p: 0.9,
          num_predict: isBigOutput ? 4096 : 2048,
        },
      }),
      signal: AbortSignal.timeout(600000),
    });

    if (!res.ok) throw new Error(`Ollama returned ${res.status}`);

    const data = await res.json();
    let content = (data.response || "").trim();

    if (data.thinking && (!content || content.length < 50)) {
      content = data.thinking.trim();
    }

    if (!content || content.length < 20) {
      throw new Error("Generated content too short");
    }

    const isHtml = type === "webpage" || type === "dashboard" || type === "document" || type === "report" || type === "summarize";

    if (isHtml) {
      content = extractHTML(content);
    }

    return {
      content,
      fileType: isHtml ? "html" : "md",
      title: `${type.charAt(0).toUpperCase() + type.slice(1)} Result`,
    };
  }

  async generate(taskId: string, type: string, prompt: string): Promise<{ content: string; fileType: string; title: string }> {
    this.fallbackUsed = false;

    try {
      return await this.tryGenerate(this.model, type, prompt);
    } catch (err: any) {
      if (this.fallbackModel) {
        console.warn(`Primary model ${this.model} failed for ${taskId}: ${err.message}. Trying fallback ${this.fallbackModel}...`);
        this.fallbackUsed = true;
        return await this.tryGenerate(this.fallbackModel, type, prompt);
      }
      throw err;
    }
  }
}

function extractHTML(text: string): string {
  const htmlStart = text.indexOf("<!DOCTYPE html>");
  const htmlStart2 = text.indexOf("<html");
  let start = htmlStart >= 0 ? htmlStart : htmlStart2 >= 0 ? htmlStart2 : -1;

  if (start >= 0) {
    const end = text.lastIndexOf("</html>");
    return end > start ? text.slice(start, end + 7).trim() : text.slice(start).trim();
  }

  const codeBlock = text.match(/```html?\n?([\s\S]*?)```/);
  return codeBlock ? codeBlock[1].trim() : text.trim();
}
